### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: ' These functions provide information about the environment in which the quantum computation is occuring.'
functions: []
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: |-
    Returns the number of qubits currently available to borrow.
    This includes unused qubits; that is, this includes the qubits
    returned by `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Returns the number of qubits currently available to use.
newtypes: []
...
